server:
  port: 8888


##mybatis
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/way?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: root
  redis:
    host: localhost
    port: 6379
    timeout: 3000ms


mybatis:
  mapper-locations: classpath:mapper/*.xml



token:
  key: eiaokiang
  expireTime: 60
